# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, 'Expired'), (1, 'Now Showing'), (1, 'Coming Soon')], default=0)),
                ('synopsis', models.TextField(max_length=1000)),
            ],
        ),
    ]
